### ISSUE TITLE
Definição de campos página ver_det.php 

### ISSUE THREAD

**Issue by momo2725** [CMCuritiba/mscmcldap#77]
**Definir campos do BD que serão implementados por views do arquivo _ver_det.php_**

```
$sql_vereador_partido = $pdoWspl->prepare("
	SELECT
		c.ver_id as ver_id,
		c.ini_nome as ini_nome,                     -- Nome do vereador
		c.ver_site as ver_site,
		c.ver_redes_sociais as ver_redes_sociais,
		c.usu_email as usu_email,
		c.ver_fone_principal as ver_fone_principal,
		c.ver_fones as ver_fones,
		c.ver_localizacao as ver_localizacao,
		c.ver_legislaturas as ver_legislaturas,
		c.partido as ver_partido,
		c.arq_id_biografia as arq_id_biografia,
		c.ver_biografia as ver_biografia 
	FROM
		spl.vereador_cerimonial c
	WHERE
		c.ini_ativa = 't'
	AND	c.ver_id = :ver_id
		  ");
```

**Comment by matheusvolanin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Escrever as issues](https://trello.com/c/0CZDzS0I/2-escrever-as-issues)

**Comment by momo2725** [comment]
View implementada e testada no BD limeira@des como detalhes_vereador

**Comment by momo2725** [comment]
- Nome --> BD
- Partido --> BD
- Legislaturas --> BD
- Gabinete/Localização --> BD
- Fone/Fones --> BD
- E-mail --> BD
- Site --> BD
- Redes Sociais --> BD
- ID e Biografia --> BD

![ver_det](https://user-images.githubusercontent.com/18397943/45899701-f4e14600-bdb3-11e8-97bf-69376269adee.png)

**Comment by momo2725** [comment]
Etapa concluída

**Comment by diemello** [comment]
Removida do servidor de teste devido a consulta já ser realizada em uma view **vereador_cerimonial** já existente.
