### ISSUE TITLE
Definição de campos página mesa.php

### ISSUE THREAD

**Issue by momo2725** [CMCuritiba/mscmcldap#78]
**Definir campos do BD que serão implementados por views do arquivo _mesa.php_**

```
$query_mesa = "SELECT cv.crg_nome AS cargo,
			v.ini_nome AS vereador,
		        cv.crg_ordem AS cargo_ordem
		        FROM spl.conjunto_vereadores cj
			JOIN spl.composicao c USING (con_id)
			JOIN spl.vereador v USING (ver_id)
			JOIN spl.cargo_vereador cv USING (crg_id)
			JOIN spl.tipo_iniciativa t USING (tin_id)
			WHERE t.tin_nome = 'Mesa' and cj.ini_ativa and t.tin_id = 9
			ORDER by cargo_ordem";
```

**Comment by matheusvolanin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Escrever as issues](https://trello.com/c/0CZDzS0I/2-escrever-as-issues)

**Comment by momo2725** [comment]
View implementada e testada no BD limeira@des como consulta_mesa

**Comment by momo2725** [comment]
- Cargo nome --> BD
- Cargo ordem --> BD
- Nome vereador --> BD

![mesa](https://user-images.githubusercontent.com/18397943/45900033-e7788b80-bdb4-11e8-81ab-3f254e82850e.png)

**Comment by momo2725** [comment]
Etapa concluída
