### ISSUE TITLE
Definição de campos página cpi_transporte.php

### ISSUE THREAD

**Issue by momo2725** [CMCuritiba/mscmcldap#79]
**Definir campos do BD que serão implementados por views do arquivo _cpi_transporte.php_**

- **Query para Atas**

```

$query_rs_destaque_noticias = "
         select ata.*, TO_CHAR(r.rec_data, 'DD/MM/YYYY') AS atc_data,
         cj.ini_nome, 
         r.rec_numero as atc_numero,
         r.rec_tipo_reuniao  as atc_tipo_sessao,
         spl.codigo_ata_comissao(ata.*) as texto 
         from spl.ata_comissao as ata, spl.conjunto_vereadores as cj, spl.reuniao_comissao r 
         where r.con_id=cj.con_id and r.rec_id = ata.rec_id and cj.con_id=5303 and ata.atc_liberada = 't' 
         ORDER BY r.rec_data DESC
            ";
```

- **Query para Requerimentos**
```

  $query_rs_destaque_noticias = "
  		SELECT
  			pro.*,
  			TO_CHAR(pro.pro_protocolada, 'DD/MM/YYYY') AS pro_data,
  			pro.pro_sumula as pro_ementa, 
  			spl.codigo_proposicao(pro.pro_id) as pro_codigo
  		FROM
  			spl.proposicao as pro
  		WHERE
  			pro.tpr_id= 129 and 
  			pro.est_id > 1
  		ORDER BY
  			pro_data DESC, spl.codigo_proposicao(pro.pro_id) DESC
            ";
```

**Comment by matheusvolanin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Escrever as issues](https://trello.com/c/0CZDzS0I/2-escrever-as-issues)

**Comment by momo2725** [comment]
Views implementadas e testadas no BD limeira@des como _atas_cpi_transporte_ e _requerimentos_cpi_transporte_

**Comment by momo2725** [comment]
A parte de links é estática, enquanto os dados da tabela são trazidos do BD.

- Número da Reunião --> BD
- Tipo da Reunião --> BD
- Data da Reunião --> BD
- Nome/Texto da Reunião --> BD


![cpi1](https://user-images.githubusercontent.com/18397943/45900210-7c7b8480-bdb5-11e8-8179-74a220db78ea.png)

- Número do Requerimento --> BD
- Ementa do Requerimento --> BD
- Data do Requerimento --> BD
- Código do Requerimento --> BD

![cpi2](https://user-images.githubusercontent.com/18397943/45900211-7d141b00-bdb5-11e8-9ee5-bd370ee9710a.png)

**Comment by momo2725** [comment]
Etapa concluída
