### ISSUE TITLE
Definição de campos página comissao.php 

### ISSUE THREAD

**Issue by momo2725** [CMCuritiba/mscmcldap#80]
**Definir campos do BD que serão implementados por views do arquivo _comissao.php_**

**Query para comissões temporárias:**

`$query_rs_comissoes_temp = "SELECT * FROM spl.comissao_site WHERE tin_id=7 ORDER BY comissao_ordem, comissao, cargo_ordem, vereador";`

**Query para comissões permanentes:**

`
$query_rs_comissoes_perm = "SELECT * FROM spl.comissao_site WHERE tin_id=6 ORDER BY comissao_ordem, comissao, cargo_ordem, vereador";`

**View implementada no BD:**

```
 SELECT t.tin_id,
    t.tin_nome AS tipo,
    cj.con_sigla,
    cj.ini_nome AS comissao,
    cj.con_descricao AS comissao_descricao,
    cj.con_site_ordem AS comissao_ordem,
    v.ini_nome AS vereador,
    cv.crg_nome AS cargo,
    cv.crg_ordem AS cargo_ordem
   FROM spl.conjunto_vereadores cj
     JOIN spl.composicao c USING (con_id)
     JOIN spl.vereador v USING (ver_id)
     JOIN spl.cargo_vereador cv USING (crg_id)
     JOIN spl.tipo_iniciativa t USING (tin_id)
  WHERE (cj.tin_id = ANY (ARRAY[6, 7])) AND cj.ini_ativa AND lower(btrim(cj.con_sigla::text)) <> 'c.especial'::text;
```
A parte abaixo em azul é estática no site. Já a parte das comissões permanentes é toda trazida pela view acima. O mesmo se repete para as comissões temporárias. As query's são diferenciadas apenas pelo campo _tin_id_.

![estatico - bd](https://user-images.githubusercontent.com/18397943/45819731-730df180-bcbb-11e8-9204-8395fde949c2.png)

**Comment by matheusvolanin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Escrever as issues](https://trello.com/c/0CZDzS0I/2-escrever-as-issues)

**Comment by momo2725** [comment]
View já implementada no BD limeira@des com nome _comissao_site_.

**Comment by momo2725** [comment]
Etapa concluída
