### ISSUE TITLE
Serviço imagem vereadores

### ISSUE THREAD

**Issue by momo2725** [CMCuritiba/mscmcldap#81]
**Definir se haverá implementação do serviço para buscar imagem do site no BD (_bio_img.php_)**

```
	        	SELECT
			    a.arq_nome as nome,
			    a.arq_tipo as arq_tipo,
			    ac.arq_anexo as arq_anexo
			FROM
			    spl.arquivo a,
			    spl.arquivo_conteudo ac
			WHERE
			    a.arq_id = ac.arq_id
			AND
			    a.arq_id = :idcodigo
```

**Comment by matheusvolanin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Escrever as issues](https://trello.com/c/0CZDzS0I/2-escrever-as-issues)

**Comment by momo2725** [comment]
Projeto pausado no momento. Fechando issue.
