### ISSUE TITLE
Serviço Dados de vereadores

### ISSUE THREAD

**Issue by diemello** [CMCuritiba/mscmcldap#83]
## Descrição 
Implementar serviço para exibir dados de vereadores no site.
Exemplo:
![image](https://user-images.githubusercontent.com/18293096/46086467-879c2f00-c17e-11e8-8b3e-6ee90635d7ed.png)

### Requisito 1 
Campos exibidos:
		

1. ver_id - identificador - integer
2. ini_nome - nome vereador - character varying
3. ver_site - site - character varying
4. ver_redes_sociais - redes sociais - character varying
5. usu_email - email - character varying
6. ver_fone_principal - fone principal - character varying
7. ver_fones - fones - character varying
8. ver_localizacao - localização - character varying
9. ver_legislaturas - legislaturas - character varying
10. partido - partido - character varying 
11. arq_id_biografia - identificador biografia - integer
12. ver_biografia - biografia - text

### Requisito 2
Buscar estes campos da view **vereador_cerimonial** no BD
https://github.com/CMCuritiba/mscmcldap/issues/77
https://github.com/CMCuritiba/mscmcldap/issues/76

### Requisito 3
Não buscar imagem do banco, o site irá trazer a foto do vereador direto pela página do Plone

**Comment by momo2725** [comment]
Serviço já implementado pelo @rodrigoferraro : https://github.com/CMCuritiba/mscmcldap/pull/92
Fechando issue.
